### PR TITLE
Refactor/rss import

### PR DESCRIPTION
**Pull request by asibs**
This PR outlines a potential way forward to break up the extremely large 'imports.js' file. The motivation for doing this is so the code is broken down into smaller chunks which are easier to read, more maintainable, more testable, and less intimidating to add functionality to.

Rather than a single `import` endpoint, which points to a very large function handling _all_ possible types of import, splitting this up into multiple endpoints - one per type of import.

The steps needed to do this for each type of import are as follows:
1) Create a new `import<type>.js` file, eg. `importrss.js` or `importtwitter.js`, etc.
2) Remove the code which renders the view for the type of import out of the large `imports.js` file and put it into the new, more specific file.
3) Find the case statement that deals with this type of import in `exports.submit`, and cut and paste it into the new file, as a new import function. This is the most time-consuming step, as the code will almost certainly require some common imports or variables from near the top of the `imports.js` file or the top of the `exports.submit` function.
4) Change the `app.js` file to require the new, specific import file, and to use the new function when rendering the view. Also create a new POST endpoint for submitting the form, using the new smaller & more specific import function.
5) Finally, change the view for this type of import to submit to the new POST endpoint.

NOTES:
- The `contextslist` variable needs to be passed into all views so the menu can use it. At the very least, the functionality for doing this should be factored out, so it can be imported into all import files rather than re-implemented in every one!
- Getting the `importContext` is also required by most/all types of importing, so again this should be factored out into a common file rather than re-implemented in every import file.
- The hidden `source` form fields are currently used to help determine the type of import being performed. With specific endpoints for each import type, this is no longer necessary, so these could be removed. The hidden field in the RSS Import View has been left in-place for now, but should be removed assuming this way forward is accepted.

As well as following the above process, this PR contains some other small unrelated changes:
- Defaulting `rssinput` and `rssitems` in the RSS Import View, so the view does not assume what the first value in `rsspresets` will be - if an installation of Infranodus has different presets, the existing hard-coding will not work as expected
- When rendering the RSS Import View, remove some unused variables which were passed, such as `evernote`, etc.
- Improving handling when `contextlists` variable is not set in `views/components/common/menu.ejs` & `views/components/entries/ContextMenu.ejs`

### CODE REVIEW

**Comment by deemeetree** [comment]
Thank you! I will take a look at this in the next days and will see how this could be integrated.

**Comment by deemeetree** [comment]
@asibs is there a way to contact you, because I wanted to discuss something related to InfraNodus and this pull request in particular. You could send me your email or messenger number / id via https://noduslabs.com/contact

Thank you!

**Comment by asibs** [comment]
> @asibs is there a way to contact you, because I wanted to discuss something related to InfraNodus and this pull request in particular. You could send me your email or messenger number / id via https://noduslabs.com/contact
> 
> Thank you!

@deemeetree - I have messaged you with my contact details via your contact form.

**Comment by asibs** [comment]
@deemeetree - any thoughts on this PR? I haven't seen anything come into my inbox from you so dar :)

**Comment by deemeetree** [comment]
@asibs hey in fact i emailed you a week ago, did you not get that email? maybe it was in your spam folder... was from info@noduslabs.com — I now sent it from another account, hopefully you get it this time!

**Comment by deemeetree** [comment]
Following your suggestion, I separated Google imports as well, see #304

**Pull request merged**
